### ISSUE TITLE
NullPointerException on empty page

### ISSUE THREAD

**Issue by pccasto** [jniesen/build-flow-http-extension-plugin#2]
Hi,
I was attempting to use your extension to trigger a remote Jenkins server to take an action using the 
Build Triggers - Trigger builds remotely (e.g., from scripts) capability.

The URL for that capability returns a 201 code, and empty content, and so causes the following:

```
java.lang.NullPointerException
    at org.codehaus.groovy.runtime.callsite.GetEffectivePojoPropertySite.acceptGetProperty(GetEffectivePojoPropertySite.java:51)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:227)
    at org.jenkinsci.plugins.buildflow.http.extension.HttpBuildFlowDSL$_get_closure1_closure2.doCall(HttpBuildFlowDSL.groovy:54)
```

Appears the " return reader.text" could be modified to handle no content case? Of course if doing something along those lines, having the the return code would be a useful improvement.  

This had seemed like a perfect use-case for your plugin (jenkins http triggering), such a shame that the build-trigger plugin creators didn't provide any content :-).

Thanks for your consideration of this issue.

**Comment by pccasto** [comment]
In case someone else runs across this.... Had hoped that the guard / rescue logic from build flow might help with trapping this problem, but it does not.  That guards against flow failures, but apparently doesn't protect against this sort of exception.

**Comment by jniesen** [comment]
Thanks for using this and help improve it. I'll have a look at your issue
tonight.
